<li id="post-job">Post</li>
<li id="unpost-job">Unpost</li>
<li id="edit-job">Edit</li>
<li class="divider"></li>
<li id="copy-job-link">Copy job link</li>
<li id="share-with-connections">Share with connections</li>
<li id="share-with-employees">Share with employees</li>
<li id="share-with-followers">Share with followers</li>
<li class="divider"></li>
<li id="delete-job">Delete</li>